FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
WORKDIR /app/apps/web

RUN npm run build

FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat g++ make python3 bash

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app ./

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["npm", "start"]
