FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install --only=development

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src ./src
COPY --from=builder /app/start.sh ./start.sh

RUN chmod +x ./start.sh

ENV NODE_ENV=development

ENTRYPOINT ["sh", "./start.sh"]
